### ISSUE TITLE
KeyError: 'make_proposal'

### ISSUE THREAD

**Issue by Timo-hab** [daijifeng001/MNC#38]
Hi, running the demo.py leads to following error:

```Traceback (most recent call last):
  File "/home/timo/MNC/tools/demo.py", line 139, in <module>
    _, _, _ = im_detect(im, net)
  File "/home/timo/MNC/tools/demo.py", line 90, in im_detect
    masks_phase1 = net.blobs['make_proposal'].data[...]
KeyError: 'make_proposal'```

**Comment by hgaiser** [comment]
Not sure where you got that piece of code from, but on master it looks different:

https://github.com/daijifeng001/MNC/blob/master/tools/demo.py#L85

**Comment by Timo-hab** [comment]
Sorry for that typo. Actually the error is the following:

```
Traceback (most recent call last):
  File "/home/timo/MNC/tools/demo.py", line 137, in <module>
    _, _, _ = im_detect(im, net)
  File "/home/timo/MNC/tools/demo.py", line 87, in im_detect
    masks_phase1 = net.blobs['mask_proposal'].data[...]
KeyError: 'mask_proposal'
```

**Comment by Timo-hab** [comment]
It turned out, I included the wrong path to prototxt (faster_rcnn_end2end instead of (mnc_5stage). Sorry.

@hgaiser 
Btw. I've seen you have a model with ResNet instead of VGG. Could please share the inference time of that network. How fast is it? Thanks!

**Comment by hgaiser** [comment]
Hey,

Ah nice that you got it working. Yeah we implemented a sort of hybrid between ResNet and the MNC VGG16 network. In my experience its giving great results. As for inference time, I don't know the exact numbers for all variants that we have. The network that I'm training right now, for which I'm using ResNet50 (3 stages) takes approximately 0.17s on a Pascal Titan X. Hope that helps, otherwise shoot me an email.

**Comment by Timo-hab** [comment]
Interesting! Yes I still have one two questions. What is your email address?  info@delftrobotics.com ?

**Comment by hgaiser** [comment]
I just updated my profile to show my email address, you can find it there.
